FROM adoptopenjdk:11-hotspot AS build
ARG VERSION

RUN apt-get update \
    && apt-get install -y unzip curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -s https://packages.couchbase.com/clients/connectors/elasticsearch/${VERSION}/couchbase-elasticsearch-connector-${VERSION}.zip -o /couchbase-elasticsearch-connector.zip \
    && unzip -o -d / /couchbase-elasticsearch-connector.zip \
    && mv /couchbase-elasticsearch-connector-${VERSION} /opt/couchbase-elasticsearch-connector



FROM adoptopenjdk:11-hotspot
COPY --from=build /opt/couchbase-elasticsearch-connector /opt/couchbase-elasticsearch-connector

ENV PATH="/opt/couchbase-elasticsearch-connector/bin:${PATH}"
VOLUME [ "/opt/couchbase-elasticsearch-connector/config", "/opt/couchbase-elasticsearch-connector/secrets" ]
EXPOSE 31415

ENTRYPOINT [ "/opt/couchbase-elasticsearch-connector/bin/cbes" ]
