= Couchbase Elasticsearch Connector

https://github.com/couchbaselabs/couchbase-elasticsearch-connector/releases[*Download*]
| https://docs.couchbase.com/elasticsearch-connector/4.0/index.html[*Documentation*]

The Couchbase Elasticsearch Connector replicates your documents from Couchbase Server to Elasticsearch in real time.
The connector service uses the high-performance Database Change Protocol (DCP) to receive notifications when documents change in Couchbase.
When a Couchbase change is saved to disk, the connector propagates the change to your Elasticsearch cluster.

NOTE: If you're looking for the Elasticsearch Plug-in flavor of the connector, that's in a https://github.com/couchbase/couchbase-elasticsearch-connector/tree/release/cypress[different branch].

== Building the connector from source

The connector distribution may be built from source with the command:

    ./gradlew build

The distribution archive will be generated under `build/distributions`.
During development, it might be more convenient to run:

    ./gradlew installDist

which creates `build/install/couchbase-elasticsearch-connector` as a `$CBES_HOME` directory.

=== IntelliJ IDEA setup
Because the project uses annotation processors, some link:INTELLIJ-SETUP.md[fiddly setup] is required when importing the project into IntelliJ IDEA.
