/*
 * Copyright 2018 Couchbase, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.couchbase.connector.util;

import java.io.File;

public class EnvironmentHelper {
  private static final String appHome = System.getenv("APP_HOME");

  //
  // MUST NOT DECLARE A LOGGER! -- Otherwise Log4J won't get read from the correct location
  // ($APP_HOME/config/log4j2.xml). See AbstractCliCommand's static init block.
  //

  static {
    // Expect the launch script generated by Gradle to set this environment variable.
    if (appHome == null) {
      System.err.println("WARNING: Environment variable 'APP_HOME' not set (launch script is responsible for this). " +
          "Assuming development environment (will resolve paths relative to src/dist)");
    }
  }

  private EnvironmentHelper() {
    throw new AssertionError("not instantiable");
  }

  public static File getInstallDir() {
    return appHome == null ? new File("src/dist") : new File(appHome);
  }
}
