= Compatibility

.Legend
* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.

* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade to a supported version.

* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

== Operating System

Linux is required for production deployments.

macOS is fine for experimentation and development, but is not officially supported.

Windows is completely untested and unsupported.

== Elasticsearch

Elasticsearch version support is informed by https://www.elastic.co/support/eol[Elastic product end of life dates].

[%autowidth,cols="^,6*^"]
|===
 |             6+h| Connector
h| Elasticsearch↓ | 4.1 | 4.2.0 - 4.2.1 | 4.2.2 - 4.2.7 | 4.2.8 - 4.2.15 | 4.3 | 4.4
 | 8.0 - 8.6      | ✖   | ✖             | ✖             | ✖              | ✖   | ✔
 | 7.14 - 7.17    | ✖   | ✖             | ✖             | ✖              | ✔   | ✔
 | 7.12 - 7.13    | ✖   | ✖             | ✖             | ✖              | ✔   | ✖
 | 7.8 - 7.11     | ✖   | ✖             | ✖             | ✔              | ✔   | ✖
 | 7.6 - 7.7      | ✖   | ✖             | ◎             | ◎              | ◎   | ✖
 | 7.4 - 7.5      | ✖   | ◎             | ◎             | ◎              | ◎   | ✖
 | 6.8.17         | ✔   | ✔             | ✔             | ✔              | ✔   | ✖
 | 5.6.16         | ◎   | ◎             | ◎             | ◎              | ✖   | ✖
|===

== OpenSearch

OpenSearch version support is informed by the https://opensearch.org/releases.html#maintenance-policy[OpenSearch Maintenance Policy].

[%autowidth,cols="^,1*^"]
|===
 |             1+h| Connector
h| OpenSearch↓    | 4.4.5 and later
 | 2.0.0 - 2.6.0  | ✔
 | 1.3.8          | ✔
 | 1.3.3 - 1.3.7  | ◎
 | 1.0.0 - 1.3.2  | ✖
|===

== Amazon OpenSearch Service

Connector versions 4.4.5 and later are compatible with Amazon OpenSearch Service.

To connect to an Amazon OpenSearch Service domain, specify the domain's hostname in the `hosts` property of the connector's `[elasticsearch]` config section.
Then specify the domain's AWS region in the `[elasticsearch.aws]` connector config section.

The connector gets AWS credentials from the https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials.html[Default Credential Provider Chain].

== Couchbase Capella

Connector versions 4.2.4 and later are compatible with Couchbase Capella.
You will need to enable xref:secure-connections.adoc[Secure Connections] in the `[couchbase]` config section.

== Couchbase Server

The connector is compatible with Couchbase Server Enterprise Edition and Couchbase Server Community Edition.

[%autowidth,cols="^,3*^"]
|===
 |                   3+h| Connector
h| Couchbase↓           | 4.1.0 - 4.2.1 | 4.2.2 - 4.3.0 | 4.3.1 and later
 | 7.0.2 and later      | ◎ *           | ✖             | ✔
 | 7.0.0 - 7.0.1        | ◎ *           | ✔             | ✔
 | 6.5 - 6.6            | ✔             | ✔             | ✔
 | 6.0                  | ✔             | ✔             | ◎
 | 5.x                  | ✔             | ◎             | ◎
 | < 5.0                | ✖             | ✖             | ✖
|===
+++*+++ If you've been using an earlier version of Couchbase, you can upgrade to Couchbase 7 and everything will continue working as before.
To take advantage of the Scopes and Collections introduced in Couchbase 7, please upgrade the connector to version 4.3 or later.

== Java

[%autowidth,cols="^,2*^"]
|===
 |                           2+h| Connector
h| Java↓                        | 4.1 - 4.2 | 4.3 - 4.4
 | OpenJDK 17 (Eclipse Temurin) | ✔         | ✔
 | OpenJDK 11 (Eclipse Temurin) | ✔         | ✔
 | OpenJDK 8 (AdoptOpenJDK)     | ✔         | ✖
 | Oracle JDK 8                 | ✔         | ✖
|===


== Consul

Only required for Autonomous Operations mode.

[%autowidth,cols="^,3*^"]
|===
 |         3+h| Connector
h| Consul↓    | 4.1 - 4.2.6  | 4.2.7 - 4.4.0 | 4.4.1 and later
 | 1.14.3     | ✖            | ✖             | ✔
 | 1.13.1     | ✖            | ✖             | ✔
 | 1.12.4     | ✖            | ✖             | ✔
 | 1.11.8     | ✖            | ✖             | ✔
 | 1.10.12    | ✖            | ✖             | ◎
 | 1.9.1      | ✖            | ✔             | ◎
 | 1.5.3      | ✔            | ✔             | ◎
|===
