= Compatibility

.Legend
* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.

* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade to a supported version.

* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

== Operating System

Linux is required for production deployments.

macOS is fine for experimentation and development, but is not officially supported.

Windows is completely untested and unsupported.

== Elasticsearch

Elasticsearch version support is informed by https://www.elastic.co/support/eol[Elastic product end of life dates].

[%autowidth,cols="^,5*^"]
|===
 |             5+h| Connector
h| Elasticsearch↓ | 4.1 | 4.2.0 - 4.2.1 | 4.2.2 - 4.2.7 | 4.2.8 - 4.2.15 | 4.3
 | 7.12 - 7.16    | ✖   | ✖             | ✖             | ✖              | ✔
 | 7.8 - 7.11     | ✖   | ✖             | ✖             | ✔              | ✔
 | 7.6 - 7.7      | ✖   | ✖             | ◎             | ◎              | ◎
 | 7.4 - 7.5      | ✖   | ◎             | ◎             | ◎              | ◎
 | 6.8.17         | ✔   | ✔             | ✔             | ✔              | ✔
 | 5.6.16         | ◎   | ◎             | ◎             | ◎              | ✖
|===

== Amazon OpenSearch Service

Direct connection to Amazon OpenSearch Service instances is supported by connector versions 4.2 and later.

== Couchbase Capella

Connector versions 4.2.4 and later are compatible with Couchbase Capella.

== Couchbase Server

The connector is compatible with Couchbase Server Enterprise Edition and Couchbase Server Community Edition.

[%autowidth,cols="^,3*^"]
|===
 |                   3+h| Connector
h| Couchbase↓           | 4.1.0 - 4.2.1 | 4.2.2 - 4.3.0 | 4.3.1+
 | 7.0.2+               | ◎ *           | ✖             | ✔
 | 7.0.0 - 7.0.1        | ◎ *           | ✔             | ✔
 | 6.x                  | ✔             | ✔             | ✔
 | 5.x                  | ✔             | ◎             | ◎
 | < 5.0                | ✖             | ✖             | ✖
|===
+++*+++ If you've been using an earlier version of Couchbase, you can upgrade to Couchbase 7 and everything will continue working as before.
To take advantage of the Scopes and Collections introduced in Couchbase 7, please upgrade the connector to version 4.3.

== Java

[%autowidth,cols="^,2*^"]
|===
 |                 2+h| Connector
h| Java↓            | 4.1 - 4.2 | 4.3
 | AdoptOpenJDK 11  | ✔         | ✔
 | AdoptOpenJDK 8   | ✔         | ✖
 | Oracle JDK 8     | ✔         | ✖
|===


== Consul

Only required for Autonomous Operations mode.

[%autowidth,cols="^,2*^"]
|===
 |         2+h| Connector
h| Consul↓    | 4.1 - 4.2.6  | 4.2.7+
 | 1.5.3      | ✔            | ✔
 | 1.9.1      | ✖            | ✔
|===
