# For the Edit on GitHub button.
gh_link: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/tree/master/docs/
# Use the Couchbase theme.
theme: couchbase-theme
# Used for redirects.
plugins:
  - jekyll-redirect-from
# To avoid port conflicts.
reload_port: 35730
# Required here because it cannot be pushed down to the couchbase-theme.
markdown: redcarpet
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]