name: Run Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '*.md'
      - '*.adoc'
      - '.gitignore'
      - '.editorconfig'
      - 'examples/**'
      - 'Dockerfile*'
      - '.github/workflows/**'
      - '!.github/workflows/run-tests.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run tests
        timeout-minutes: 60
        run: |
          ./gradlew --no-build-cache --continue integrationTest || true

      - name: Publish test results
        run: |
          curl https://raw.githubusercontent.com/couchbaselabs/junit-markdown/refs/heads/main/JunitMarkdown.java --output ${{ runner.temp }}/JunitMarkdown.java
          java ${{ runner.temp }}/JunitMarkdown.java . >> $GITHUB_STEP_SUMMARY
